### ISSUE TITLE
"Top" domains only?

### ISSUE THREAD

**Issue by isaackwan** [hildjj/node-acme#11]
Hello,

While looking at the [library](https://github.com/hildjj/node-acme/blob/e1a3a67dbea29da38c02f56f344ba50644e12df1/lib/acme.js#L271), I noticed that only domain names at the top level (sorry, I'm not sure about the terminology here) are accepted. That means example.com is OK but s1.example.com is not. I tried to look into that in the ACME spec and also Google but with no luck. I wonder if you can give me a few pointers on that restriction?

Thanks
-Isaac

**Comment by bifurcation** [comment]
This would be a bug, but the relevant code has been removed. I think the intent is to support subdomains as well, but that will be a something to check once the relevant things have been rebuilt.
